import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from 'next/link'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className="h-[100%]">
      <body className={inter.className + ' prose dark:prose-invert !max-w-[100%] pt-2 relative min-h-screen h-[100%]'}>
        <header className="flex justify-between pb-5 px-4 sm:px-10 md:px-28">
          <nav>
            <Link href="/">
              <span className="text-3xl text-center">Word-overflow</span>
            </Link>
          </nav>
        </header>
        {children}
      </body>
    </html>
  )
}
