import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + ' prose dark:prose-invert !max-w-[100%] px-4 sm:px-10 md:px-28 pt-2 relative min-h-screen'
        }
      >
        {children}
      </body>
    </html>
  )
}
